//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Core.Resources.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralMessagesAr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralMessagesAr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Core.Resources.General.GeneralMessagesAr", typeof(GeneralMessagesAr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نجاح العملية.
        /// </summary>
        public static string actionSuccess {
            get {
                return ResourceManager.GetString("actionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا , فشل في اضافة البيانات.
        /// </summary>
        public static string addFailed {
            get {
                return ResourceManager.GetString("addFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل البيانات بنجاح.
        /// </summary>
        public static string addSuccess {
            get {
                return ResourceManager.GetString("addSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا , فشل في حذف البيانات.
        /// </summary>
        public static string deleteFailed {
            get {
                return ResourceManager.GetString("deleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف البيانات بنجاح.
        /// </summary>
        public static string deleteSuccess {
            get {
                return ResourceManager.GetString("deleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملية فاشلة.
        /// </summary>
        public static string errorActionFailed {
            get {
                return ResourceManager.GetString("errorActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا , لا توجد بيانات.
        /// </summary>
        public static string errorDataNotFound {
            get {
                return ResourceManager.GetString("errorDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  الوصف لا يمكن أن يكون أطول من {0} حرف.
        /// </summary>
        public static string errorDescriptionMaxLength {
            get {
                return ResourceManager.GetString("errorDescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود التعرف مطلوب.
        /// </summary>
        public static string errorIdIsRequired {
            get {
                return ResourceManager.GetString("errorIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، البريد الإلكتروني غير صالح.
        /// </summary>
        public static string errorInvalidEmail {
            get {
                return ResourceManager.GetString("errorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، رابط فيسبوك غير صالح.
        /// </summary>
        public static string errorInvalidFacebookUrl {
            get {
                return ResourceManager.GetString("errorInvalidFacebookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، رابط انستجرام غير صالح.
        /// </summary>
        public static string errorInvalidInstagramUrl {
            get {
                return ResourceManager.GetString("errorInvalidInstagramUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، رابط لينكدان غير صالح.
        /// </summary>
        public static string errorInvalidLinkedinUrl {
            get {
                return ResourceManager.GetString("errorInvalidLinkedinUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا ، رقم الهاتف غير صالح.
        /// </summary>
        public static string ErrorInvalidPhoneNumber {
            get {
                return ResourceManager.GetString("ErrorInvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، رقم الهاتف {0} غير صالح.
        /// </summary>
        public static string ErrorInvalidPhoneNumbers {
            get {
                return ResourceManager.GetString("ErrorInvalidPhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، رابط تويتر غير صالح.
        /// </summary>
        public static string errorInvalidTwitterUrl {
            get {
                return ResourceManager.GetString("errorInvalidTwitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، رابط الموقع غير صالح.
        /// </summary>
        public static string errorInvalidWebsiteUrl {
            get {
                return ResourceManager.GetString("errorInvalidWebsiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، رابط اليوتيوب غير صالح.
        /// </summary>
        public static string errorInvalidYoutubeUrl {
            get {
                return ResourceManager.GetString("errorInvalidYoutubeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، يجب إدخال رمز الدولة.
        /// </summary>
        public static string errorIsRequiredCountryCode {
            get {
                return ResourceManager.GetString("errorIsRequiredCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، يجب إدخال اسم رمز الدولة.
        /// </summary>
        public static string errorIsRequiredCountryCodeName {
            get {
                return ResourceManager.GetString("errorIsRequiredCountryCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، يجب إدخال رمز الاتصال.
        /// </summary>
        public static string errorIsRequiredDialCode {
            get {
                return ResourceManager.GetString("errorIsRequiredDialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، يجب إدخال رقم الهاتف.
        /// </summary>
        public static string errorIsRequiredPhoneNumber {
            get {
                return ResourceManager.GetString("errorIsRequiredPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، يجب إدخال الاسم.
        /// </summary>
        public static string errorNameIsRequired {
            get {
                return ResourceManager.GetString("errorNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول الاسم لا يمكن أن يتجاوز {0} حرفًا..
        /// </summary>
        public static string errorNameLength {
            get {
                return ResourceManager.GetString("errorNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إرسال البيانات.
        /// </summary>
        public static string errorNoData {
            get {
                return ResourceManager.GetString("errorNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إرسال بيانات تسجيل الدخول.
        /// </summary>
        public static string errorSendLoginData {
            get {
                return ResourceManager.GetString("errorSendLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، حدث خطأ، يرجى الاتصال بالإدارة.
        /// </summary>
        public static string errorSomthingWrong {
            get {
                return ResourceManager.GetString("errorSomthingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملية ناجحة.
        /// </summary>
        public static string operationSuccess {
            get {
                return ResourceManager.GetString("operationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، فشل تعديل البيانات.
        /// </summary>
        public static string updateFailed {
            get {
                return ResourceManager.GetString("updateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث البيانات بنجاح..
        /// </summary>
        public static string updateSuccess {
            get {
                return ResourceManager.GetString("updateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إضافته مسبقًا..
        /// </summary>
        public static string wasAddedBefore {
            get {
                return ResourceManager.GetString("wasAddedBefore", resourceCulture);
            }
        }
    }
}
