//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Core.Resources.UsersModules.User {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsersMessagesAr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsersMessagesAr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Core.Resources.UsersModules.User.UsersMessagesAr", typeof(UsersMessagesAr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، يجب إدخال بريد المستخدم الإلكتروني.
        /// </summary>
        public static string errorEmailIsRequired {
            get {
                return ResourceManager.GetString("errorEmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال رقم الهاتف أو البريد الإلكتروني أو اسم المستخدم لتسجيل الدخول..
        /// </summary>
        public static string errorInvalidLoginData {
            get {
                return ResourceManager.GetString("errorInvalidLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، بيانات تسجيل الدخول غير صالحة..
        /// </summary>
        public static string errorInvalidUserLoginData {
            get {
                return ResourceManager.GetString("errorInvalidUserLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، يجب إدخال كلمة السر.
        /// </summary>
        public static string errorPasswordRequired {
            get {
                return ResourceManager.GetString("errorPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف مطلوب.
        /// </summary>
        public static string errorPhoneNumberIsRequired {
            get {
                return ResourceManager.GetString("errorPhoneNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد الاتصال بالمستخدم قد تم إضافته بالفعل.
        /// </summary>
        public static string errorUserContactEmailWasAdded {
            get {
                return ResourceManager.GetString("errorUserContactEmailWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، المستخدم غير موجود.
        /// </summary>
        public static string errorUserDoesNotExists {
            get {
                return ResourceManager.GetString("errorUserDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد المستخدم الإلكتروني قد تم إضافته بالفعل.
        /// </summary>
        public static string errorUserEmailWasAdded {
            get {
                return ResourceManager.GetString("errorUserEmailWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، يجب إدخال اسم تسجيل الدخول للمستخدم.
        /// </summary>
        public static string errorUserLoginNameIsRequired {
            get {
                return ResourceManager.GetString("errorUserLoginNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم تسجيل الدخول للمستخدم قد تم إضافته بالفعل.
        /// </summary>
        public static string errorUserLoginNameWasAdded {
            get {
                return ResourceManager.GetString("errorUserLoginNameWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، يجب إدخال اسم المستخدم.
        /// </summary>
        public static string errorUsernameIsRequired {
            get {
                return ResourceManager.GetString("errorUsernameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم قد تم إضافته بالفعل.
        /// </summary>
        public static string errorUsernameWasAdded {
            get {
                return ResourceManager.GetString("errorUsernameWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال كلمة السر ..
        /// </summary>
        public static string errorUserPasswordIsRequired {
            get {
                return ResourceManager.GetString("errorUserPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف قد تم إضافته مسبقًا.
        /// </summary>
        public static string errorUserPhoneNumberWasAdded {
            get {
                return ResourceManager.GetString("errorUserPhoneNumberWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا، نوع المستخدم غير صالح.
        /// </summary>
        public static string errorUserTypeInvalid {
            get {
                return ResourceManager.GetString("errorUserTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الدخول بنجاح.
        /// </summary>
        public static string loginSuccess {
            get {
                return ResourceManager.GetString("loginSuccess", resourceCulture);
            }
        }
    }
}
